# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  ca.vehiclereg1.example.com:
    image: hyperledger/fabric-ca:1.4.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vehiclereg1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.vehiclereg1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7867f0b7e6f67e0c0b03e714253fd1462352d7d7258ab5261ce90c632ca35d06_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.vehiclereg1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7867f0b7e6f67e0c0b03e714253fd1462352d7d7258ab5261ce90c632ca35d06_sk -b admin:adminpw -d --cfg.identities.allowremove'
    volumes:
      - ./crypto-config/peerOrganizations/vehiclereg1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.vehiclereg1.example.com
    networks:
      - byfn

  ca.nadra2.example.com:
    image: hyperledger/fabric-ca:1.4.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nadra2.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.nadra2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e1f3c10dc355c2c8518beca39afa8452887f0b64da95d26752f59ddf49c91715_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.nadra2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e1f3c10dc355c2c8518beca39afa8452887f0b64da95d26752f59ddf49c91715_sk -b admin:adminpw -d --cfg.identities.allowremove'
    volumes:
      - ./crypto-config/peerOrganizations/nadra2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.nadra2.example.com
    networks:
      - byfn